kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-one
  template:
    metadata:
      labels:
        app: app-one
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.10
        env:
        - name: MESSAGE
          value: "Hello from app1."
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: app-one
spec:
  selector:
    app: app-one
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
# ---
# kind: Ingress
# apiVersion: networking.k8s.io/v1
# metadata:
#   name: app-one
# spec:
#   rules:
#   - host : app1.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: app-one
#             port:
#               number: 80