Vagrant.configure("2") do |config|
  # Mount the conf folder into the VM at /vagrant_data
  config.vm.synced_folder "./conf", "/vagrant_data"

  config.vm.define "lwilliamS" do |server|
    server.vm.box = "generic/debian12"
    server.vm.hostname = "lwilliamS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "vmware_desktop" do |vm|
      vm.force_vmware_license = "workstation"
      vm.vmx["memsize"] = "1024"
      vm.vmx["numvcpus"] = "1"
    end

    server.vm.provision "shell", inline: <<-SHELL
      apt-get update

      # Install K3s in server mode with the correct IP for the node
      curl -sfL https://get.k3s.io | sh -s - server \
        --cluster-init \
        --node-ip 192.168.56.110 \
        --advertise-address 192.168.56.110 \
        --tls-san=192.168.56.110

      # Apply your K8s manifests using kubectl
      kubectl apply -f /vagrant_data/app1.yaml
      kubectl apply -f /vagrant_data/app2.yaml
      kubectl apply -f /vagrant_data/app3.yaml
      kubectl apply -f /vagrant_data/ingress.yaml
    SHELL
  end
end
