Vagrant.configure("2") do |config|
  config.vm.synced_folder "./conf", "/vagrant_data"
  config.vm.define "serverS" do |config|
    config.vm.box = "generic/debian12"
    config.vm.hostname = "serverS"
    config.vm.network "private_network", ip: "192.168.56.110"
    master.vm.provider "vmware_desktop" do |vm|
      vm.vmx["memsize"] = "1024"
      vm.vmx["numvcpus"] = "1"   
    end
    config.vm.provision "shell", inline: <<-SHELL
      apt-get update
      curl -sfL https://get.k3s.io | sh -s - server --cluster-init --tls-san=192.168.56.110
      kubectl apply -f /vagrant_data/app1.yaml
      kubectl apply -f /vagrant_data/app2.yaml
      kubectl apply -f /vagrant_data/app3.yaml
      kubectl apply -f /vagrant_data/ingress.yaml
    SHELL
  end
end