Vagrant.configure("2") do |config|
  config.vm.synced_folder "./data", "/vagrant_data"
  config.vm.define "VagrantS" do |master|
    master.vm.box = "generic/debian12"
    master.vm.hostname = "VagrantS"
    master.vm.network "private_network", ip: "192.168.56.110"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    master.vm.provision "shell", inline: <<-SHELL
      apt-get update
      curl -sfL https://get.k3s.io | sh -
      cp /var/lib/rancher/k3s/server/node-token /vagrant_data
    SHELL
  end

  config.vm.define "workerSW" do |control|
    control.vm.box = "generic/debian12"
    control.vm.hostname = "workerSW"
    control.vm.network "private_network", ip: "192.168.56.111"
    control.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    control.vm.provision "shell", inline: <<-SHELL
      apt-get update
      cat /vagrant_data/node-token
      curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=$(cat /vagrant_data/node-token) sh -
    SHELL
  end
end

# apt-get install -y docker.io
# systemctl enable docker
# systemctl start docker
# apt-get update
# apt-get install -y apt-transport-https ca-certificates curl gpg
# mkdir -p -m 755 /etc/apt/keyrings
# curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
# echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
# apt-get update
# apt-get install -y kubelet kubeadm kubectl
# apt-mark hold kubelet kubeadm kubectl

# export PATH=$PATH:/sbin // for ifconfig to work
# ip addr show eth1 // alt to show eth1 adpter

# https://docs.k3s.io/datastore/ha-embedded
