Vagrant.configure("2") do |config|
  # config.vm.synced_folder "./data", "/vagrant_data"
  config.vm.define "serverS" do |config|
    config.vm.box = "generic/debian12"
    config.vm.hostname = "serverS"
    config.vm.network "private_network", ip: "192.168.56.110"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    config.vm.provision "shell", inline: <<-SHELL
      apt-get update
      curl -sfL https://get.k3s.io | sh -
      # cp /var/lib/rancher/k3s/server/node-token /vagrant_data
    SHELL
  end
end